version: "3.9"
services:
  web:
    build: .
    ports:
      - 8888:8080
  db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: "buyme"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "user_password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
